### ISSUE TITLE
Add examples

### ISSUE THREAD

**Issue by ordovicia** [pfnet-research/k8s-cluster-simulator#149]

**Comment by dtaniwaki** [comment]
I think an example has been added.

**Comment by ordovicia** [comment]
I thought it would be better to have another example, but the status quo is fine.

**Comment by dtaniwaki** [comment]
Ah, I didn’t think you were going to add more examples. That’s why I singularizad the directory name. We should make it plural when we will put more examples. 

By the way, we can include common submitters in the package after making the hard-coded values configurable so others don’t have to copy and paste the code.
